[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "0.1.1"
version_files = ["core/build.gradle.kts:version", "README.md:<version>", "README.md:implementation"]
update_changelog_on_bump = true
major_version_zero = true
